name: Set proxy
description: 
inputs:
  config:
    description: ''
    required: true
runs:
  using: "composite"
  steps:
    - name: Install
      shell: bash
      env:
        config: ${{ inputs.config }}
      run: |
        sudo apt-get install shadowsocks-libev simple-obfs proxychains-ng
        sudo -E sh -c 'echo $config|base64 -d > /etc/shadowsocks-libev/config.json'
        sudo systemctl start shadowsocks-libev
        sleep 5s

        sudo sed -i 's/socks4 	127.0.0.1 9050/socks5 127.0.0.1 1080/g' /etc/proxychains4.conf
        sudo sed -i 's/#quiet_mode/quiet_mode/g' /etc/proxychains4.conf

        defaultdns=`grep "nameserver" /etc/resolv.conf`
        sudo sed -i "s/nameserver .*/nameserver 1.1.1.1/" /etc/resolv.conf
        #sudo sed -i "s/nameserver .*/$defaultdns/" /etc/resolv.conf

    - name: Test
      uses: nick-invision/retry@v2
      with:
        timeout_minutes: 10
        max_attempts: 3
        retry_wait_seconds: 60
        command: |
          for i in {1..2}
          do
            (proxychains curl -I -s --connect-timeout 5 https://example.com; break) || (\
            echo connect error; \
            systemctl status --no-pager shadowsocks-libev; \
            sleep 5s)
          done
          proxychains curl -I -s --connect-timeout 5 https://example.com || (\
          echo connect error; \
          systemctl status --no-pager shadowsocks-libev; \
          exit 1)
